### ISSUE TITLE
exception not a valid header name

### ISSUE THREAD

**Issue by basz** [zendframework/zend-diactoros#198]
Not sure what is going on? Could it be http2 related?

generated by: It's comes Charles's "Copy Curl Request" feature
```
curl -H ':method: POST' -H ':scheme: https' -H ':path: /identity/update-display-name' -H ':authority: api-development.plhw.nl' -H 'accept: application/json, text/javascript, */*; q=0.01' -H 'content-type: application/json; charset=UTF-8' -H 'origin: http://localhost:4200' -H 'accept-encoding: gzip, deflate' -H 'content-length: 72' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7' -H 'referer: http://localhost:4200/account/settings' -H 'dnt: 1' -H 'accept-language: en-us' --data-binary '{"user_id":"6fc88c51-c16a-4612-9b8b-e48e15931689","display_name":"BasK"}' 'https://api-development.plhw.nl/identity/update-display-name' | gunzip
```
Errors with:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   479  100   407  100    72    970    171 --:--:-- --:--:-- --:--:--   973
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: &quot;&quot; is not valid header name in /home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php:150
Stack trace:
#0 /home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/RequestTrait.php(329): Zend\Diactoros\HeaderSecurity::assertValidName('')
#1 /home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/RequestTrait.php(70): Zend\Diactoros\ServerRequest-&gt;assertHeaders(Array)
#2 /home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/ServerRequest.php(96): Zend\Diactoros\ServerRequest-&gt;initialize(Object(Zend\Diactoros\Uri), 'POST', Object(Zend\Diactoros\PhpInputStream), Array)
#3 /home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/ServerRequestFactory.php(73): Zend\Diactoros\ServerRequest-&gt;__const in <b>/home-projects/api-plhw-development/deploy/releases/20160529202409UTC/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php</b> on line <b>150</b><br />
```

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-diactoros; a new issue has been opened at https://github.com/laminas/laminas-diactoros/issues/17.
